spring.application.name=publication-service
spring.cloud.config.uri=http://ec2-16-171-142-15.eu-north-1.compute.amazonaws.com:8888
spring.config.import=configserver:
eureka.client.service-url.defaultZone=http://ec2-16-171-142-15.eu-north-1.compute.amazonaws.com:8761/eureka
server.tomcat.max-threads=4
spring.jpa.open-in-view=false
cloudinary.cloud_name=dkovjoflq
cloudinary.api_key=472878483678624
cloudinary.api_secret=0tO86aslulZR6-5eDxWF4RmLAs
