spring.application.name=publication-service
spring.cloud.config.uri=http://ec2-16-171-110-76.eu-north-1.compute.amazonaws.com:8888
spring.config.import=configserver:
eureka.client.service-url.defaultZone=http://ec2-16-171-110-76.eu-north-1.compute.amazonaws.com:8761/eureka
server.tomcat.max-threads=4
spring.jpa.open-in-view=false
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

